apiVersion: v1
kind: Pod
metadata:
  name: memcached
  namespace: test 
spec:
  containers:
  - name: memcached
    image: memcached
    resources:
      limits:
        memory: "1Gi"
        cpu : "200m"